apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sterling-devops-deploy
  namespace: default
spec:
  params:
    - name: ibm-entitlement-key
      description: "IBM entitlement key. If not set, will use secret manager."
      type: string
      default: "false"
  tasks:
    - name: get-ibm-entitlement-key
      when:
        - input: "$(params.ibm-entitlement-key)"
          operator: in
          values: ["false"]
      taskRef:
        name: ibmcloud-secrets-manager-get
        kind: Task
      retries: 2
      params:
        - name: KEY_ID
          value: 968d7819-f2c5-7b67-c420-3c6bfd51521e
        - name: SECRETS_MANAGER_ENDPOINT_URL
          value: >-
            https://afa20521-cd75-4864-843f-e59fd0ffd49d.us-south.secrets-manager.appdomain.cloud

    - name: set-ibm-entitlement-key
      runAfter:
        - get-ibm-entitlement-key
      params:
        - name: ibm-entitlement-key
          value: "$(params.ibm-entitlement-key)"
      retries: 3
      taskSpec:
        params:
          - name: ibm-entitlement-key
        results:
          - name: effective-entitlement-key
            description: The resolved entitlement key
        steps:
          - name: echo-entitlement-key
            image: quay.io/devfile/universal-developer-image:latest
            script: |
              #!/usr/bin/env bash
              set -e
              if [ "$(params.ibm-entitlement-key)" == "false" ]; then
                echo "Using TechZone provided entitlement key"
                echo -n "$(tasks.get-ibm-entitlement-key.results.secret-value)" > $(results.effective-entitlement-key.path)
              else
                echo "Using user provided entitlement key"
                echo -n "$(params.ibm-entitlement-key)" > $(results.effective-entitlement-key.path)
              fi

    - name: sterling-install
      runAfter:
        - set-ibm-entitlement-key
      taskSpec:
        steps:
          - name: install-sterling
            image: quay.io/kishorec/sde:latest
            script: |
              #!/bin/bash
              set -e

              export ENTITLED_REGISTRY_KEY="$(tasks.set-ibm-entitlement-key.results.effective-entitlement-key)"
              export ANSIBLE_CONFIG=./ansible.cfg
              export SI_INSTANCEID=dev01
              export SI_VERSION=6.2.0.3

              echo "Cloning Sterling automation repository"
              git clone https://github.com/ckpkishore/ansible-ibm-sterling.git
              cd ansible-ibm-sterling

              ls -ltr

              # Set Helm version
              HELM_VERSION=v3.18.3

              # Download and extract Helm
              curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
              tar -zxvf helm.tar.gz

              # Move helm binary to a local bin directory (e.g., /workspace/bin) and add to PATH
              mkdir -p /workspace/bin
              mv linux-amd64/helm /workspace/bin/helm
              chmod +x /workspace/bin/helm

              # Add it to PATH
              export PATH="/workspace/bin:$PATH"

              # Verify installation
              helm version

              echo "Running Sterling install via Ansible..."
              ansible-playbook playbooks/deploy_sb2b.yml
              echo "Ansible playbook finished"


