apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sterling-devops-deploy
  namespace: default
spec:
  params:
    - default: 'false'
      description: 'IBM entitlement key. If not set, will use secret manager.'
      name: ibm-entitlement-key
      type: string
  tasks:
    - name: get-ibm-entitlement-key
      params:
        - name: KEY_ID
          value: 968d7819-f2c5-7b67-c420-3c6bfd51521e
        - name: SECRETS_MANAGER_ENDPOINT_URL
          value: 'https://afa20521-cd75-4864-843f-e59fd0ffd49d.us-south.secrets-manager.appdomain.cloud'
      retries: 2
      taskRef:
        kind: Task
        name: ibmcloud-secrets-manager-get
      when:
        - input: $(params.ibm-entitlement-key)
          operator: in
          values:
            - 'false'
    - name: set-ibm-entitlement-key
      params:
        - name: ibm-entitlement-key
          value: $(params.ibm-entitlement-key)
      retries: 3
      runAfter:
        - get-ibm-entitlement-key
      taskSpec:
        metadata: {}
        params:
          - name: ibm-entitlement-key
            type: string
        results:
          - description: The resolved entitlement key
            name: effective-entitlement-key
            type: string
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/devfile/universal-developer-image:latest'
            name: echo-entitlement-key
            script: |
              #!/usr/bin/env bash
              set -e
              if [ "$(params.ibm-entitlement-key)" == "false" ]; then
                echo "Using TechZone provided entitlement key"
                echo -n "$(tasks.get-ibm-entitlement-key.results.secret-value)" > $(results.effective-entitlement-key.path)
              else
                echo "Using user provided entitlement key"
                echo -n "$(params.ibm-entitlement-key)" > $(results.effective-entitlement-key.path)
              fi
    - name: b2bi-install
      runAfter:
        - set-ibm-entitlement-key
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/kishorec/sde:latest'
            name: install-b2bi
            script: |
              #!/bin/bash
              set -e

              export ENTITLED_REGISTRY_KEY="$(tasks.set-ibm-entitlement-key.results.effective-entitlement-key)"
              export ANSIBLE_CONFIG=./ansible.cfg

              export SI_INSTANCEID=dev01
              export SI_VERSION=6.2.1.1

              echo "Cloning Sterling automation repository"
              git clone https://github.com/ckpkishore/ansible-ibm-sterling.git
              cd ansible-ibm-sterling

              ls -ltr

              # Set Helm version
              HELM_VERSION=v3.18.3

              # Download and extract Helm
              curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
              tar -zxvf helm.tar.gz

              # Move helm binary to a local bin directory (e.g., /workspace/bin) and add to PATH
              mkdir -p /workspace/bin
              mv linux-amd64/helm /workspace/bin/helm
              chmod +x /workspace/bin/helm

              # Add it to PATH
              export PATH="/workspace/bin:$PATH"

              # Verify installation
              helm version

              echo "Running B2BI install via Ansible..."
              ansible-playbook playbooks/deploy_sb2b.yml
              echo "B2BI Ansible playbook finished"
    - name: sterling-import-resources
      runAfter:
        - b2bi-install
      taskSpec:
        params:
          - name: pod-name
            description: Name of the target pod
            default: s0-b2bi-asi-server-0
          - name: namespace
            description: Namespace of the pod
            default: ibm-b2bi-dev01-app
          - name: secret-name
            default: si-system-passphrase-secret
          - name: secret-key
            default: SYSTEM_PASSPHRASE
        steps:
          - name: fetch-configurations
            image: quay.io/openshift/origin-cli:4.15
            script: |
              #!/bin/sh
              set -e
              echo "Extracting secret from OCP..."
              value=$(oc get secret -n $(params.namespace) "$(params.secret-name)" -o "jsonpath={.data.$(params.secret-key)}" | base64 -d)
              echo "The secret value is: $value"

              echo "Downloading TXExportConfig.xml from GitHub..."
              curl -sSL -o TXExportConfig.xml https://raw.githubusercontent.com/ckpkishore/sde/refs/heads/main/sfg/TXExportConfig.xml
              echo "Downloaded TXExportConfig.xml"
              sleep 10
              echo "Copying TXExportConfig.xml to pod $(params.pod-name)..."
              oc cp TXExportConfig.xml $(params.namespace)/$(params.pod-name):/tmp/TXExportConfig.xml
              echo "Copied TXExportConfig.xml"
              echo "Running import script inside pod $(params.pod-name)..."
              oc exec -n $(params.namespace) $(params.pod-name) \
                -- bash -c "/ibm/b2bi/install/tp_import/import.sh -input /tmp/TXExportConfig.xml -passphrase $value -update -errors errors.txt"
              echo "TXExportConfig.xml import complete"

              echo "Downloading customer_overrides.properties from GitHub..."
              curl -sSL -o customer_overrides.properties https://raw.githubusercontent.com/ckpkishore/sde/refs/heads/main/sfg/customer_overrides.properties
              echo "Downloaded customer_overrides.properties"
              sleep 10
              echo "Importing customer_overrides.properties..."
              oc create configmap s0-b2bi-config-property --from-file=customer_overrides.properties -n $(params.namespace) --dry-run=client -o yaml | oc apply -f -
              echo "customer_overrides.properties import complete"

              echo "Downloading IBM_SDE_Troubleshooting_Agent.ipynb from GitHub..."
              curl -fSL -o IBM_SDE_Troubleshooting_Agent.ipynb https://raw.githubusercontent.com/ckpkishore/sde/refs/heads/main/notebook/IBM_SDE_Troubleshooting_Agent.ipynb
              echo "Downloaded IBM_SDE_Troubleshooting_Agent.ipynb"
              sleep 10
              echo "Copying IBM_SDE_Troubleshooting_Agent.ipynb to pod $(params.pod-name)..."
              oc cp IBM_SDE_Troubleshooting_Agent.ipynb $(params.namespace)/$(params.pod-name):/tmp/IBM_SDE_Troubleshooting_Agent.ipynb
              echo "Copied IBM_SDE_Troubleshooting_Agent.ipynb"

              echo "Downloading sfgSFTPDemoScenario.xml from GitHub..."
              curl -sSL -o sfgSFTPDemoScenario.xml https://raw.githubusercontent.com/Knickkennedy/ibm-sterling-automation/36eea647f7ceba2624df44b91e46c29f61a940a9/roles/sb2bi_scenario_sftp/files/sfgSFTPDemoScenario.xml
              echo "Downloaded sfgSFTPDemoScenario.xml"
              sleep 10
              echo "Copying sfgSFTPDemoScenario.xml to pod $(params.pod-name)..."
              oc cp sfgSFTPDemoScenario.xml $(params.namespace)/$(params.pod-name):/tmp/sfgSFTPDemoScenario.xml
              echo "Copied sfgSFTPDemoScenario.xml"
              echo "Running import script inside pod $(params.pod-name)..."
              oc exec -n $(params.namespace) $(params.pod-name) \
                -- bash -c "/ibm/b2bi/install/tp_import/import.sh -input /tmp/sfgSFTPDemoScenario.xml -passphrase $value -update -errors errors.txt"
              echo "sfgSFTPDemoScenario.xml import complete"

              echo "Downloading PGP_DEMO_export.xml from GitHub..."
              curl -sSL -o PGP_DEMO_export.xml https://raw.githubusercontent.com/Knickkennedy/ibm-sterling-automation/36eea647f7ceba2624df44b91e46c29f61a940a9/roles/sb2bi_scenario_sftp/files/PGP_DEMO_export.xml
              echo "Downloaded PGP_DEMO_export.xml"
              sleep 10
              echo "Copying PGP_DEMO_export.xml to pod $(params.pod-name)..."
              oc cp PGP_DEMO_export.xml $(params.namespace)/$(params.pod-name):/tmp/PGP_DEMO_export.xml
              echo "Copied PGP_DEMO_export.xml"
              echo "Running import script inside pod $(params.pod-name)..."
              oc exec -n $(params.namespace) $(params.pod-name) \
                -- bash -c "/ibm/b2bi/install/tp_import/import.sh -input /tmp/PGP_DEMO_export.xml -passphrase $value -update -errors errors.txt"
              echo "PGP_DEMO_export.xml import complete"

              sleep 120
    - name: ssp-install
      runAfter:
        - set-ibm-entitlement-key
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/kishorec/sde:latest'
            name: install-ssp
            script: |
              #!/bin/bash
              set -e

              export ENTITLED_REGISTRY_KEY="$(tasks.set-ibm-entitlement-key.results.effective-entitlement-key)"
              export ANSIBLE_CONFIG=./ansible.cfg

              export SSP_INSTANCEID=dev01
              export SSP_VERSION=6.2.1.0-iFix00-2025-07-04

              echo "Cloning Sterling automation repository"
              git clone https://github.com/ckpkishore/ansible-ibm-sterling.git
              cd ansible-ibm-sterling

              ls -ltr

              # Set Helm version
              HELM_VERSION=v3.18.3

              # Download and extract Helm
              curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
              tar -zxvf helm.tar.gz

              # Move helm binary to a local bin directory (e.g., /workspace/bin) and add to PATH
              mkdir -p /workspace/bin
              mv linux-amd64/helm /workspace/bin/helm
              chmod +x /workspace/bin/helm

              # Add it to PATH
              export PATH="/workspace/bin:$PATH"

              # Verify installation
              helm version

              echo "Running SSP install via Ansible..."
              ansible-playbook playbooks/deploy_ssp.yml
              echo "SSP Ansible playbook finished"
    - name: seas-install
      runAfter:
        - set-ibm-entitlement-key
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/kishorec/sde:latest'
            name: install-seas
            script: |
              #!/bin/bash
              set -e

              export ENTITLED_REGISTRY_KEY="$(tasks.set-ibm-entitlement-key.results.effective-entitlement-key)"
              export ANSIBLE_CONFIG=./ansible.cfg

              export SEAS_INSTANCEID=dev01
              export SEAS_VERSION=6.1.0.2.03

              echo "Cloning Sterling automation repository"
              git clone https://github.com/ckpkishore/ansible-ibm-sterling.git
              cd ansible-ibm-sterling

              ls -ltr

              # Set Helm version
              HELM_VERSION=v3.18.3

              # Download and extract Helm
              curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
              tar -zxvf helm.tar.gz

              # Move helm binary to a local bin directory (e.g., /workspace/bin) and add to PATH
              mkdir -p /workspace/bin
              mv linux-amd64/helm /workspace/bin/helm
              chmod +x /workspace/bin/helm

              # Add it to PATH
              export PATH="/workspace/bin:$PATH"

              # Verify installation
              helm version

              echo "Running SEAS install via Ansible..."
              ansible-playbook playbooks/deploy_seas.yml
              echo "SEAS Ansible playbook finished"
    - name: scc-install
      runAfter:
        - set-ibm-entitlement-key
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/kishorec/sde:latest'
            name: install-scc
            script: |
              #!/bin/bash
              set -e

              export ENTITLED_REGISTRY_KEY="$(tasks.set-ibm-entitlement-key.results.effective-entitlement-key)"
              export ANSIBLE_CONFIG=./ansible.cfg

              export SCC_PRODUCTS=CCM
              export SCC_INSTANCEID=dev01
              export SCC_VERSION=6.4.0.0.iFix01_2025-05-19

              echo "Cloning Sterling automation repository"
              git clone https://github.com/ckpkishore/ansible-ibm-sterling.git
              cd ansible-ibm-sterling

              ls -ltr

              # Set Helm version
              HELM_VERSION=v3.18.3

              # Download and extract Helm
              curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
              tar -zxvf helm.tar.gz

              # Move helm binary to a local bin directory (e.g., /workspace/bin) and add to PATH
              mkdir -p /workspace/bin
              mv linux-amd64/helm /workspace/bin/helm
              chmod +x /workspace/bin/helm

              # Add it to PATH
              export PATH="/workspace/bin:$PATH"

              # Verify installation
              helm version

              echo "Running SCC install via Ansible..."
              ansible-playbook playbooks/deploy_scc.yml
              echo "SCC Ansible playbook finished"
    - name: cd-install
      runAfter:
        - set-ibm-entitlement-key
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/kishorec/sde:latest'
            name: install-cd
            script: |
              #!/bin/bash
              set -e

              export ENTITLED_REGISTRY_KEY="$(tasks.set-ibm-entitlement-key.results.effective-entitlement-key)"
              export ANSIBLE_CONFIG=./ansible.cfg

              export CD_NODENAME=CDNODE01
              export CD_NAMESPACE=ibm-cd-dev01-app
              export CD_VERSION=6.4.0.2-iFix008-2025-08-21

              echo "Cloning Sterling automation repository"
              git clone https://github.com/ckpkishore/ansible-ibm-sterling.git
              cd ansible-ibm-sterling

              ls -ltr

              # Set Helm version
              HELM_VERSION=v3.18.3

              # Download and extract Helm
              curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
              tar -zxvf helm.tar.gz

              # Move helm binary to a local bin directory (e.g., /workspace/bin) and add to PATH
              mkdir -p /workspace/bin
              mv linux-amd64/helm /workspace/bin/helm
              chmod +x /workspace/bin/helm

              # Add it to PATH
              export PATH="/workspace/bin:$PATH"

              # Verify installation
              helm version

              echo "Running CD install via Ansible..."
              ansible-playbook playbooks/deploy_cd.yml
              echo "CD Ansible playbook finished"
    - name: cdws-install
      runAfter:
        - set-ibm-entitlement-key
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/kishorec/sde:latest'
            name: install-cdws
            script: |
              #!/bin/bash
              set -e

              export ENTITLED_REGISTRY_KEY="$(tasks.set-ibm-entitlement-key.results.effective-entitlement-key)"
              export ANSIBLE_CONFIG=./ansible.cfg

              export CDWS_NAMESPACE=ibm-cdws-dev01-app
              export CDWS_VERSION=6.4.0.2_ifix001

              echo "Cloning Sterling automation repository"
              git clone https://github.com/ckpkishore/ansible-ibm-sterling.git
              cd ansible-ibm-sterling

              ls -ltr

              # Set Helm version
              HELM_VERSION=v3.18.3

              # Download and extract Helm
              curl -fsSL -o helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
              tar -zxvf helm.tar.gz

              # Move helm binary to a local bin directory (e.g., /workspace/bin) and add to PATH
              mkdir -p /workspace/bin
              mv linux-amd64/helm /workspace/bin/helm
              chmod +x /workspace/bin/helm

              # Add it to PATH
              export PATH="/workspace/bin:$PATH"

              # Verify installation
              helm version

              echo "Running CDWS install via Ansible..."
              ansible-playbook playbooks/deploy_cdws.yml
              echo "CDWS Ansible playbook finished"
    - name: minio-install
      runAfter:
        - set-ibm-entitlement-key
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/kishorec/sde:latest'
            name: install-minio
            script: |
              #!/bin/bash
              set -e

              export ENTITLED_REGISTRY_KEY="$(tasks.set-ibm-entitlement-key.results.effective-entitlement-key)"
              export ANSIBLE_CONFIG=./ansible.cfg

              export MINIO_NAMESPACE=ibm-minio

              echo "Cloning Sterling automation repository"
              git clone https://github.com/ckpkishore/ansible-ibm-sterling.git
              cd ansible-ibm-sterling

              ls -ltr

              echo "Running Minio install via Ansible..."
              ansible-playbook playbooks/tools/minio.yml
              echo "Minio Ansible playbook finished"
    - name: kafka-install
      runAfter:
        - b2bi-install
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/kishorec/sde:latest'
            name: install-kafka
            script: |
              #!/bin/bash
              set -e

              export ANSIBLE_CONFIG=./ansible.cfg

              export SI_INSTANCE_ID=dev01

              echo "Cloning Sterling automation repository"
              git clone https://github.com/ckpkishore/ansible-ibm-sterling.git
              cd ansible-ibm-sterling

              ls -ltr

              echo "Running Kafka install via Ansible..."
              ansible-playbook playbooks/tools/kafka.yml
              echo "Kafka Ansible playbook finished"
    - name: kowl-install
      runAfter:
        - kafka-install
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/kishorec/sde:latest'
            name: install-kowl
            script: |
              #!/bin/bash
              set -e

              export ANSIBLE_CONFIG=./ansible.cfg

              export SI_INSTANCE_ID=dev01

              echo "Cloning Sterling automation repository"
              git clone https://github.com/ckpkishore/ansible-ibm-sterling.git
              cd ansible-ibm-sterling

              ls -ltr

              echo "Running Kowl install via Ansible..."
              ansible-playbook playbooks/tools/kowl.yml
              echo "Kowl Ansible playbook finished"
